/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{vue,js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "tertiary-fixed": "#89f5e7",
        "on-secondary-container": "#fffbff",
        "secondary-fixed": "#eaddff",
        "on-secondary-fixed": "#25005a",
        "tertiary-fixed-dim": "#6bd8cb",
        "primary": "var(--color-primary)",
        "surface-bright": "var(--bg-surface-bright)",
        "on-primary": "var(--color-on-primary)",
        "on-surface-variant": "var(--text-on-surface-variant)",
        "surface-tint": "#3755c3",
        "primary-fixed-dim": "#b8c4ff",
        "outline": "var(--border-outline)",
        "inverse-surface": "#213145",
        "surface-container-high": "var(--bg-surface-container-high)",
        "on-secondary-fixed-variant": "#5a00c6",
        "secondary-fixed-dim": "#d2bbff",
        "primary-fixed": "#dde1ff",
        "on-secondary": "#ffffff",
        "background": "var(--bg-surface)",
        "on-surface": "var(--text-on-surface)",
        "surface-container-lowest": "var(--bg-surface-container-lowest)",
        "error-container": "#ffdad6",
        "surface-container-low": "var(--bg-surface-container-low)",
        "surface-container": "var(--bg-surface-container)",
        "tertiary": "#003c36",
        "on-primary-fixed-variant": "#173bab",
        "primary-container": "var(--color-primary-container)",
        "surface": "var(--bg-surface)",
        "on-tertiary": "#ffffff",
        "secondary-container": "var(--color-secondary-container)",
        "secondary": "var(--color-secondary)",
        "tertiary-container": "#00554e",
        "on-tertiary-container": "#5fcdbf",
        "error": "#ba1a1a",
        "on-primary-container": "#a8b8ff",
        "inverse-primary": "#b8c4ff",
        "outline-variant": "var(--border-outline-variant)",
        "on-background": "var(--text-on-background)",
        "surface-dim": "var(--bg-surface-dim)",
        "on-tertiary-fixed": "#00201d",
        "surface-variant": "var(--bg-surface-container-highest)",
        "inverse-on-surface": "#eaf1ff",
        "on-tertiary-fixed-variant": "#005049",
        "surface-container-highest": "var(--bg-surface-container-highest)",
        "on-error": "#ffffff",
        "on-primary-fixed": "#001453",
        "on-error-container": "#93000a"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      fontFamily: {
        "sans": ["Inter", "sans-serif"],
        "mono": ["JetBrains Mono", "monospace"]
      }
    },
  },
  plugins: [],
}
